<?php

########################################################################
# Extension Manager/Repository config file for ext: "bgm_theme_silicaLighting"
#
# Auto generated by Extension Builder 2012-04-26
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Helper for T3 devs',
    'description' => 'Takes some copy/paste things from T3 devs',
    'category' => 'development',
    'author' => 'Tina Westner',
    'author_email' => 'info@tina-westner.de',
    'author_company' => 'Tina Westner - Freelancer',
    'shy' => '',
    'priority' => '',
    'module' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.2.0',
    'constraints' => array(
        'depends' => array(
            'typo3' => '10.4.0-10.4.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
